spring:
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/kotlin-api-demo?currentSchema=public
    username: postgres
    password: postgres
  flyway:
    url: jdbc:postgresql://localhost:5432/kotlin-api-demo?currentSchema=public
    user: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
