{
 "title": "user",
 "time": { "from": "now-8m", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "GET /user RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum without (exported_instance,error_type, http_response_status_code) (rate(http_server_request_duration_seconds_count{http_request_method=\"GET\", http_route=\"/user\"}[1m]))"
    }
   ]
  },
  {
   "title": "GET /user 200",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{http_request_method=\"GET\",http_route=\"/user\",http_response_status_code=\"200\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GET /user 5xx",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{http_request_method=\"GET\",http_route=\"/user\",http_response_status_code=~\"5.+\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "GET /user 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n    sum(rate(\n        http_server_request_duration_seconds_bucket{http_request_method=\"GET\"}[$__interval]\n    )) by (http_request_method,le)\n)"
    }
   ]
  },
  {
   "title": "POST /user RPS",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "sum without (exported_instance,error_type, http_response_status_code) (rate(http_server_request_duration_seconds_count{http_request_method=\"POST\", http_route=\"/user\"}[1m]))"
    }
   ]
  },
  {
   "title": "POST /user 201",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{http_request_method=\"POST\",http_route=\"/user\",http_response_status_code=\"201\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "POST /user 5xx",
   "type": "heatmap",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 7 },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_bucket{http_request_method=\"POST\",http_route=\"/user\",http_response_status_code=~\"5.+\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "POST /user 99th percentile",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.99,\n    sum(rate(\n        http_server_request_duration_seconds_bucket{http_request_method=\"POST\"}[$__interval]\n    )) by (http_request_method,le)\n)"
    }
   ]
  }
 ]
}