scrape_configs:
  - job_name: 'otel-collector'
    scrape_interval: 5s
    static_configs:
      - targets: [ 'kotlin-api-demo-otel-collector:8888' ]
      - targets: [ 'kotlin-api-demo-otel-collector:8889' ]
